import type {
  ActivityEntry,
  Bin,
  DeviceModel,
  InventorySettings,
  InventoryState,
  Part,
} from "./inventory-types";

export const inventoryStorageKey = "novatech-inventory-phase1";

export const seedBins: Bin[] = [
  {
    id: "bin-canon-fusers",
    code: "A-01",
    name: "Canon Fuser Shelf",
    description: "High-touch Canon heat and fuser parts.",
    aisle: "A",
    row: 1,
    column: 1,
    manufacturer: "Canon",
    status: "active",
  },
  {
    id: "bin-canon-path",
    code: "A-02",
    name: "Canon Feed Path",
    description: "Rollers, pads, and paper path kits.",
    aisle: "A",
    row: 1,
    column: 2,
    manufacturer: "Canon",
    status: "active",
  },
  {
    id: "bin-hp-mono",
    code: "B-01",
    name: "HP Mono Stock",
    description: "Mono LaserJet feed and separation parts.",
    aisle: "B",
    row: 2,
    column: 1,
    manufacturer: "HP",
    status: "active",
  },
  {
    id: "bin-xerox-transfer",
    code: "B-02",
    name: "Xerox Transfer",
    description: "Transfer belts and rollers for AltaLink units.",
    aisle: "B",
    row: 2,
    column: 2,
    manufacturer: "Xerox",
    status: "active",
  },
  {
    id: "bin-ricoh-service",
    code: "C-01",
    name: "Ricoh Service",
    description: "Service kit parts and maintenance cartridges.",
    aisle: "C",
    row: 3,
    column: 1,
    manufacturer: "Ricoh",
    status: "active",
  },
  {
    id: "bin-universal",
    code: "C-02",
    name: "Universal Kits",
    description: "Shared consumables and field kits.",
    aisle: "C",
    row: 3,
    column: 2,
    manufacturer: "Universal",
    status: "active",
  },
  {
    id: "bin-model-cards",
    code: "D-01",
    name: "Model Cards",
    description: "Reference labels, model sheets, and barcode tags.",
    aisle: "D",
    row: 4,
    column: 1,
    manufacturer: null,
    status: "active",
  },
  {
    id: "bin-review",
    code: "D-02",
    name: "Review / Quarantine",
    description: "Items awaiting identification or bin assignment.",
    aisle: "D",
    row: 4,
    column: 2,
    manufacturer: null,
    status: "inactive",
    notes: "Use for parts that need review before they are shelved.",
  },
  {
    id: "bin-overflow",
    code: "E-01",
    name: "Overflow Bin",
    description: "Short-term overflow for new intake.",
    aisle: "E",
    row: 5,
    column: 1,
    manufacturer: null,
    status: "active",
  },
  {
    id: "bin-field-kit",
    code: "E-02",
    name: "Field Kit Drawer",
    description: "Mobile kit items and quick adjust stock.",
    aisle: "E",
    row: 5,
    column: 2,
    manufacturer: "Universal",
    status: "active",
  },
];

export const seedModels: DeviceModel[] = [
  {
    id: "canon-c5840",
    manufacturer: "Canon",
    name: "imageRUNNER ADVANCE DX C5840",
    series: "DX",
    status: "active",
  },
  {
    id: "canon-c3530",
    manufacturer: "Canon",
    name: "imageRUNNER ADVANCE DX C3530",
    series: "DX",
    status: "active",
  },
  {
    id: "hp-m607",
    manufacturer: "HP",
    name: "LaserJet Enterprise M607",
    series: "Enterprise",
    status: "active",
  },
  {
    id: "hp-m608",
    manufacturer: "HP",
    name: "LaserJet Enterprise M608",
    series: "Enterprise",
    status: "active",
  },
  {
    id: "ricoh-c3000",
    manufacturer: "Ricoh",
    name: "IM C3000",
    series: "IM",
    status: "active",
  },
  {
    id: "sharp-mx4141",
    manufacturer: "Sharp",
    name: "MX-4141N",
    series: "MX",
    status: "active",
  },
  {
    id: "konica-c360i",
    manufacturer: "Konica Minolta",
    name: "bizhub C360i",
    series: "bizhub",
    status: "active",
  },
  {
    id: "xerox-c8130",
    manufacturer: "Xerox",
    name: "AltaLink C8130",
    series: "AltaLink",
    status: "active",
  },
  {
    id: "riso-comcolor",
    manufacturer: "Riso",
    name: "ComColor GL 9730",
    series: "ComColor",
    status: "active",
  },
  {
    id: "legacy-c3300",
    manufacturer: "Canon",
    name: "imageRUNNER C3300 Series",
    series: "Legacy",
    status: "inactive",
    notes: "Keep for older installed units until the fleet refresh is complete.",
  },
];

export const seedParts: Part[] = [
  {
    id: "part-fm1-d581",
    partNumber: "FM1-D581",
    partName: "Fixing Assembly",
    manufacturer: "Canon",
    category: "Fuser",
    binId: "bin-canon-fusers",
    quantityOnHand: 4,
    reorderPoint: 3,
    reorderTarget: 8,
    compatibleModelIds: ["canon-c5840", "canon-c3530"],
    universal: false,
    notes: "High-priority repair kit. Keep one in the field kit drawer.",
    receivedAt: "2026-04-02T15:24:00.000Z",
    updatedAt: "2026-05-05T18:10:00.000Z",
    lastCountedAt: "2026-05-05T18:10:00.000Z",
  },
  {
    id: "part-fc5-8421",
    partNumber: "FC5-8421",
    partName: "Pickup Roller Kit",
    manufacturer: "Canon",
    category: "Roller",
    binId: "bin-canon-path",
    quantityOnHand: 18,
    reorderPoint: 10,
    reorderTarget: 20,
    compatibleModelIds: ["canon-c5840", "canon-c3530", "legacy-c3300"],
    universal: false,
    notes: "Common wear item. Used for paper feed complaints.",
    receivedAt: "2026-04-14T11:40:00.000Z",
    updatedAt: "2026-05-03T09:30:00.000Z",
    lastCountedAt: "2026-05-03T09:30:00.000Z",
  },
  {
    id: "part-rm2-0014",
    partNumber: "RM2-0014",
    partName: "Separation Pad",
    manufacturer: "HP",
    category: "Roller",
    binId: "bin-hp-mono",
    quantityOnHand: 7,
    reorderPoint: 15,
    reorderTarget: 24,
    compatibleModelIds: ["hp-m607", "hp-m608"],
    universal: false,
    notes: "Review reorder this week. Pull from the mono shelf first.",
    receivedAt: "2026-04-17T10:15:00.000Z",
    updatedAt: "2026-05-06T12:05:00.000Z",
    lastCountedAt: "2026-05-06T12:05:00.000Z",
  },
  {
    id: "part-cb3-90a1",
    partNumber: "CB3-90A1",
    partName: "Transfer Belt",
    manufacturer: "Xerox",
    category: "Transfer",
    binId: "bin-xerox-transfer",
    quantityOnHand: 1,
    reorderPoint: 3,
    reorderTarget: 6,
    compatibleModelIds: ["xerox-c8130"],
    universal: false,
    notes: "Critical low. Keep tagged for quick pull.",
    receivedAt: "2026-03-28T14:10:00.000Z",
    updatedAt: "2026-05-02T16:45:00.000Z",
    lastCountedAt: "2026-05-02T16:45:00.000Z",
  },
  {
    id: "part-d0-1532",
    partNumber: "D0-1532",
    partName: "Fuser Film Sleeve",
    manufacturer: "Ricoh",
    category: "Fuser",
    binId: "bin-ricoh-service",
    quantityOnHand: 12,
    reorderPoint: 6,
    reorderTarget: 16,
    compatibleModelIds: ["ricoh-c3000"],
    universal: false,
    notes: "Service parts for Ricoh IM units.",
    receivedAt: "2026-04-10T08:00:00.000Z",
    updatedAt: "2026-05-01T13:00:00.000Z",
    lastCountedAt: "2026-05-01T13:00:00.000Z",
  },
  {
    id: "part-mx-trn-44",
    partNumber: "MX-TRN-44",
    partName: "Transfer Roller",
    manufacturer: "Sharp",
    category: "Roller",
    binId: "bin-overflow",
    quantityOnHand: 9,
    reorderPoint: 8,
    reorderTarget: 18,
    compatibleModelIds: ["sharp-mx4141"],
    universal: false,
    notes: "Awaiting transfer to the Sharp section.",
    receivedAt: "2026-04-22T09:15:00.000Z",
    updatedAt: "2026-04-29T14:30:00.000Z",
    lastCountedAt: "2026-04-29T14:30:00.000Z",
  },
  {
    id: "part-c1-10x",
    partNumber: "C1-10X",
    partName: "Drum Unit",
    manufacturer: "Konica Minolta",
    category: "Drum",
    binId: "bin-field-kit",
    quantityOnHand: 0,
    reorderPoint: 2,
    reorderTarget: 6,
    compatibleModelIds: ["konica-c360i"],
    universal: false,
    notes: "Expired unit. Replace immediately.",
    receivedAt: "2026-03-20T13:20:00.000Z",
    updatedAt: "2026-05-06T08:20:00.000Z",
    lastCountedAt: "2026-05-06T08:20:00.000Z",
  },
  {
    id: "part-unv-9j12",
    partNumber: "UNV-9J12",
    partName: "Universal Feed Kit",
    manufacturer: "Universal",
    category: "Accessory",
    binId: "bin-universal",
    quantityOnHand: 3,
    reorderPoint: 5,
    reorderTarget: 12,
    compatibleModelIds: [
      "canon-c5840",
      "hp-m607",
      "ricoh-c3000",
      "sharp-mx4141",
      "xerox-c8130",
    ],
    universal: true,
    notes: "Cross-platform kit used by field techs for urgent repairs.",
    receivedAt: "2026-04-11T12:00:00.000Z",
    updatedAt: "2026-05-05T11:20:00.000Z",
    lastCountedAt: "2026-05-05T11:20:00.000Z",
  },
  {
    id: "part-hp-tnr-77",
    partNumber: "HP-TNR-77",
    partName: "Waste Toner Kit",
    manufacturer: "HP",
    category: "Maintenance",
    binId: "bin-hp-mono",
    quantityOnHand: 2,
    reorderPoint: 4,
    reorderTarget: 10,
    compatibleModelIds: ["hp-m607", "hp-m608"],
    universal: false,
    notes: "Low stock and usually paired with feed kit replacements.",
    receivedAt: "2026-04-20T16:30:00.000Z",
    updatedAt: "2026-05-04T10:05:00.000Z",
    lastCountedAt: "2026-05-04T10:05:00.000Z",
  },
  {
    id: "part-can-sns-18",
    partNumber: "CAN-SNS-18",
    partName: "Sensor Board",
    manufacturer: "Canon",
    category: "Sensor",
    binId: null,
    quantityOnHand: 5,
    reorderPoint: 5,
    reorderTarget: 12,
    compatibleModelIds: [],
    universal: false,
    notes: "Needs identification before being shelved.",
    receivedAt: "2026-04-06T07:45:00.000Z",
    updatedAt: "2026-05-06T15:15:00.000Z",
    lastCountedAt: "2026-05-06T15:15:00.000Z",
  },
  {
    id: "part-riso-ink-12",
    partNumber: "RISO-INK-12",
    partName: "Master Ink Cartridge",
    manufacturer: "Riso",
    category: "Maintenance",
    binId: "bin-model-cards",
    quantityOnHand: 20,
    reorderPoint: 8,
    reorderTarget: 24,
    compatibleModelIds: ["riso-comcolor"],
    universal: false,
    notes: "Stored near reference cards because it is requested with every GL visit.",
    receivedAt: "2026-04-08T10:00:00.000Z",
    updatedAt: "2026-05-01T09:45:00.000Z",
    lastCountedAt: "2026-05-01T09:45:00.000Z",
  },
  {
    id: "part-xrx-fdr-05",
    partNumber: "XRX-FDR-05",
    partName: "Feed Roller",
    manufacturer: "Xerox",
    category: "Roller",
    binId: "bin-xerox-transfer",
    quantityOnHand: 6,
    reorderPoint: 6,
    reorderTarget: 14,
    compatibleModelIds: ["xerox-c8130"],
    universal: false,
    notes: "Keep on hand for standard service calls.",
    receivedAt: "2026-04-16T14:00:00.000Z",
    updatedAt: "2026-05-02T08:10:00.000Z",
    lastCountedAt: "2026-05-02T08:10:00.000Z",
  },
  {
    id: "part-km-blade-14",
    partNumber: "KM-BLADE-14",
    partName: "Cleaning Blade",
    manufacturer: "Konica Minolta",
    category: "Maintenance",
    binId: "bin-field-kit",
    quantityOnHand: 14,
    reorderPoint: 10,
    reorderTarget: 20,
    compatibleModelIds: ["konica-c360i"],
    universal: false,
    notes: "Packaging is small enough to live in the field kit drawer.",
    receivedAt: "2026-04-19T11:10:00.000Z",
    updatedAt: "2026-05-05T17:30:00.000Z",
    lastCountedAt: "2026-05-05T17:30:00.000Z",
  },
  {
    id: "part-shr-fan-03",
    partNumber: "SHR-FAN-03",
    partName: "Cooling Fan Kit",
    manufacturer: "Sharp",
    category: "Accessory",
    binId: "bin-review",
    quantityOnHand: 1,
    reorderPoint: 4,
    reorderTarget: 8,
    compatibleModelIds: ["sharp-mx4141"],
    universal: false,
    notes: "Awaiting bin assignment after the last count.",
    receivedAt: "2026-03-31T12:00:00.000Z",
    updatedAt: "2026-05-03T16:00:00.000Z",
    lastCountedAt: "2026-05-03T16:00:00.000Z",
  },
  {
    id: "part-hp-cln-11",
    partNumber: "HP-CLN-11",
    partName: "Charge Roller",
    manufacturer: "HP",
    category: "Roller",
    binId: "bin-hp-mono",
    quantityOnHand: 26,
    reorderPoint: 12,
    reorderTarget: 30,
    compatibleModelIds: ["hp-m607", "hp-m608"],
    universal: false,
    notes: "Healthy stock level; good candidate for a quick-scan part tag.",
    receivedAt: "2026-04-04T13:50:00.000Z",
    updatedAt: "2026-05-04T18:40:00.000Z",
    lastCountedAt: "2026-05-04T18:40:00.000Z",
  },
];

export const seedActivity: ActivityEntry[] = [
  {
    id: "activity-adjust-hp",
    action: "adjusted",
    tone: "info",
    entityType: "inventory",
    entityId: "part-hp-cln-11",
    title: "Charge Roller counted",
    detail: "HP-CLN-11 was counted at 26 units during the last walk-through.",
    occurredAt: "2026-05-04T18:40:00.000Z",
  },
  {
    id: "activity-print-tag",
    action: "printed",
    tone: "success",
    entityType: "part",
    entityId: "part-fm1-d581",
    title: "Part tag printed",
    detail: "Printed a replenishment tag for FM1-D581 and routed it to the fuser shelf.",
    occurredAt: "2026-05-05T18:15:00.000Z",
  },
  {
    id: "activity-location",
    action: "moved",
    tone: "warning",
    entityType: "bin",
    entityId: "bin-overflow",
    title: "Overflow bin reassigned",
    detail: "MX-TRN-44 was moved to overflow while the Sharp aisle is rearranged.",
    occurredAt: "2026-04-29T14:30:00.000Z",
  },
  {
    id: "activity-import",
    action: "imported",
    tone: "success",
    entityType: "system",
    entityId: "seed",
    title: "Demo dataset loaded",
    detail: "Typed mock inventory seed was loaded for explicit local demo mode.",
    occurredAt: "2026-04-02T15:00:00.000Z",
  },
  {
    id: "activity-attention",
    action: "updated",
    tone: "warning",
    entityType: "part",
    entityId: "part-can-sns-18",
    title: "Sensor board flagged for review",
    detail: "CAN-SNS-18 still needs a location and compatibility assignment.",
    occurredAt: "2026-05-06T15:15:00.000Z",
  },
  {
    id: "activity-low-stock",
    action: "adjusted",
    tone: "danger",
    entityType: "part",
    entityId: "part-c1-10x",
    title: "Drum unit hit zero",
    detail: "C1-10X is at zero quantity and should be reordered immediately.",
    occurredAt: "2026-05-06T08:20:00.000Z",
  },
];

export const seedSettings: InventorySettings = {
  lowStockThreshold: 5,
  defaultPrintCopies: 1,
  storageMode: "browser-local",
  syncMode: "mock-phase-1",
  theme: "dark",
  updatedAt: "2026-05-06T15:15:00.000Z",
};

export function createDefaultSettings(storageMode: InventorySettings["storageMode"] = "browser-local"): InventorySettings {
  return {
    lowStockThreshold: 5,
    defaultPrintCopies: 1,
    storageMode,
    syncMode: storageMode === "supabase" ? "supabase" : "mock-phase-1",
    theme: "dark",
    updatedAt: new Date().toISOString(),
  };
}

export function createEmptyState(
  storageMode: InventorySettings["storageMode"] = "browser-local",
): InventoryState {
  return {
    bins: [],
    models: [],
    parts: [],
    activity: [],
    settings: createDefaultSettings(storageMode),
  };
}

export function createSeedState(): InventoryState {
  return {
    bins: structuredClone(seedBins),
    models: structuredClone(seedModels),
    parts: structuredClone(seedParts),
    activity: structuredClone(seedActivity),
    settings: structuredClone(seedSettings),
  };
}
